###
DELETE http://localhost:5555/api/notes/34f7b5d0-5c1d-43e7-99c0-7bf91ac8dfd1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiI1MzEzMWM2MC0wYzRlLTQ0NWYtOGM0NS0xMjY2MzVjOWMzMmMiLCJuYmYiOjE3NjMxNjUxNTksImV4cCI6MTc2MzE2Njk1OSwiaWF0IjoxNzYzMTY1MTU5LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.qJYKqIi_t_WZFS-dToVQMzSBBOtkmec1peJ6q352j5k

###
GET http://localhost:5555/api/notes/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiI1MzEzMWM2MC0wYzRlLTQ0NWYtOGM0NS0xMjY2MzVjOWMzMmMiLCJuYmYiOjE3NjMxNjUxNTksImV4cCI6MTc2MzE2Njk1OSwiaWF0IjoxNzYzMTY1MTU5LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.qJYKqIi_t_WZFS-dToVQMzSBBOtkmec1peJ6q352j5k

###
GET http://localhost:5555/api/notes/34f7b5d0-5c1d-43e7-99c0-7bf91ac8dfd1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiI1MzEzMWM2MC0wYzRlLTQ0NWYtOGM0NS0xMjY2MzVjOWMzMmMiLCJuYmYiOjE3NjMxNjUxNTksImV4cCI6MTc2MzE2Njk1OSwiaWF0IjoxNzYzMTY1MTU5LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.qJYKqIi_t_WZFS-dToVQMzSBBOtkmec1peJ6q352j5k

###
POST http://localhost:5555/api/notes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiI1MzEzMWM2MC0wYzRlLTQ0NWYtOGM0NS0xMjY2MzVjOWMzMmMiLCJuYmYiOjE3NjMxNjUxNTksImV4cCI6MTc2MzE2Njk1OSwiaWF0IjoxNzYzMTY1MTU5LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.qJYKqIi_t_WZFS-dToVQMzSBBOtkmec1peJ6q352j5k

{
    "title": "Most Important Shell Commands",
    "body": "cd, ls & pwd"
}

###
PUT http://localhost:5555/api/notes/34f7b5d0-5c1d-43e7-99c0-7bf91ac8dfd1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiI1MzEzMWM2MC0wYzRlLTQ0NWYtOGM0NS0xMjY2MzVjOWMzMmMiLCJuYmYiOjE3NjMxNjUxNTksImV4cCI6MTc2MzE2Njk1OSwiaWF0IjoxNzYzMTY1MTU5LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.qJYKqIi_t_WZFS-dToVQMzSBBOtkmec1peJ6q352j5k

{
    "title": "Most Important Bash Commands",
    "body": "cd, ls & pwd"
}
