###
DELETE http://localhost:5555/api/notes/5ff17ee2-2432-4ee4-8f67-f1ce1e00a9fb/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiIyNjJlM2MxYi02MjdmLTRiODUtOWEwYS02ZTA2YWViMzE4ZTgiLCJuYmYiOjE3NjMxNTMyMjQsImV4cCI6MTc2MzE1NTAyNCwiaWF0IjoxNzYzMTUzMjI0LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.yVOJG7Ps2QzcMC_DS46Uf_YW4CEsfL04ErZRgiZcPaE

###
GET http://localhost:5555/api/notes/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiIyNjJlM2MxYi02MjdmLTRiODUtOWEwYS02ZTA2YWViMzE4ZTgiLCJuYmYiOjE3NjMxNTMyMjQsImV4cCI6MTc2MzE1NTAyNCwiaWF0IjoxNzYzMTUzMjI0LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.yVOJG7Ps2QzcMC_DS46Uf_YW4CEsfL04ErZRgiZcPaE

###
GET http://localhost:5555/api/notes/5ff17ee2-2432-4ee4-8f67-f1ce1e00a9fb/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiIyNjJlM2MxYi02MjdmLTRiODUtOWEwYS02ZTA2YWViMzE4ZTgiLCJuYmYiOjE3NjMxNTMyMjQsImV4cCI6MTc2MzE1NTAyNCwiaWF0IjoxNzYzMTUzMjI0LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.yVOJG7Ps2QzcMC_DS46Uf_YW4CEsfL04ErZRgiZcPaE

###
POST http://localhost:5555/api/notes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiIyNjJlM2MxYi02MjdmLTRiODUtOWEwYS02ZTA2YWViMzE4ZTgiLCJuYmYiOjE3NjMxNTMyMjQsImV4cCI6MTc2MzE1NTAyNCwiaWF0IjoxNzYzMTUzMjI0LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.yVOJG7Ps2QzcMC_DS46Uf_YW4CEsfL04ErZRgiZcPaE

{
    "title": "Most Important Shell Commands",
    "body": "cd, ls & pwd"
}

###
PUT http://localhost:5555/api/notes/5ff17ee2-2432-4ee4-8f67-f1ce1e00a9fb/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbmEiLCJzdWIiOiIyNjJlM2MxYi02MjdmLTRiODUtOWEwYS02ZTA2YWViMzE4ZTgiLCJuYmYiOjE3NjMxNTMyMjQsImV4cCI6MTc2MzE1NTAyNCwiaWF0IjoxNzYzMTUzMjI0LCJpc3MiOiI8aXNzdWVyPiIsImF1ZCI6IjxhdWRpZW5jZT4ifQ.yVOJG7Ps2QzcMC_DS46Uf_YW4CEsfL04ErZRgiZcPaE

{
    "title": "Most Important Bash Commands",
    "body": "cd, ls & pwd"
}
